# For technical reasons, this file is *NOT* reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Stephanie Stroka
email: stephanie.stroka@digitalid.net
description: This is the personal webpage of Stephanie Stroka
url: http://www.stephaniestroka.com
permalink: pretty
paginate: 5
paginate_path: /news/:num/
date_format: "%e %B %Y" # http://strftime.net
#google_analytics: UA-29309650-1

plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: ""
    values:
      layout: main
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "assets/threesixtyfive"
    values:
      threesixtyfive: true 

# Table of Contents:
# <h2 data-toc-text="Short Text">Longer Text</h2>
# <h2 data-toc-skip>Heading is Skipped in TOC</h2>
